server:
  port: 9100
management:
  metrics:
    web:
      server:
        auto-time-requests: false # 关闭自动检测请求
# 配置datasource信息
spring:
  datasource:
    username: root
    password: LqtMysql123@$
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 30
      maxWait: 50000
# 指定zipkin持久化介质为mysql
zipkin:
  storage:
    type: mysql
