eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9800/eureka/
server:
  port: 9527
spring:
  application:
    name: proxy-user
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"