server:
  port: 9900

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9800/eureka  ## 注册到 eureka
spring:
  application:
    name: serv-user  ## 应用程序名称，后面会在消费者中用到
  datasource:
    username: root
    password: LqtMysql123@$
    url: jdbc:mysql://localhost:3306/lqt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lqt.user.entity